import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Container } from "@/components/ui/Container";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { EditorialHero } from "@/components/editorial/EditorialHero";
import { RelatedObjects } from "@/components/editorial/RelatedObjects";
import { SourceList } from "@/components/ui/SourceList";
import { JsonLd } from "@/components/seo/JsonLd";
import { GraphConnections } from "@/components/graph/GraphConnections";
import { EntityImagery } from "@/components/media/EntityImagery";
import { EntityRecommendations } from "@/components/graph/EntityRecommendations";
import { EntityDataPanel } from "@/components/graph/EntityDataPanel";
import { EntityQualityPanel } from "@/components/authority/EntityQualityPanel";
import { EntityProvenancePanel } from "@/components/authority/EntityProvenancePanel";
import { getStandaloneEntities } from "@/knowledge-graph";
import { engine } from "@/platform/data-engine";
import { buildMetadata } from "@/lib/seo/metadata";
import { breadcrumbSchema, collectionPageSchema, type Crumb } from "@/lib/seo/jsonld";
import { ROUTES } from "@/lib/routes";

export const dynamicParams = false;

export function generateStaticParams() {
  return getStandaloneEntities().map((e) => {
    const sep = e.id.indexOf(":");
    return { type: e.id.slice(0, sep), slug: e.id.slice(sep + 1) };
  });
}

export async function generateMetadata({
  params,
}: PageProps<"/explore/entity/[type]/[slug]">): Promise<Metadata> {
  const { type, slug } = await params;
  // Metadata is generated by the platform's universal metadata system from the
  // resolved entity runtime — one source for every facet.
  const rt = engine.entity.resolveByTypeSlug(type, slug);
  if (!rt) return {};
  const meta = engine.metadata.for(rt);
  return buildMetadata({
    title: meta.seo.title,
    description: meta.seo.description,
    path: rt.canonicalPath,
  });
}

export default async function GraphEntityPage({
  params,
}: PageProps<"/explore/entity/[type]/[slug]">) {
  const { type, slug } = await params;
  // Everything flows through the Scientific Data Engine — no manual assembly.
  const resolved = engine.entity.resolveByTypeSlug(type, slug);
  // Entities with their own content entry are served there, not here.
  if (!resolved || resolved.entries.length > 0) notFound();

  const typeLabel = resolved.typeLabel;
  const url = resolved.canonicalPath;
  const related = resolved.related;
  const siblings = engine.recommendation.sameType(resolved.id);
  const hasConnections = resolved.connections.length > 0;

  const crumbs: Crumb[] = [
    { name: "Home", url: "/" },
    { name: "Explore", url: ROUTES.explore },
    { name: resolved.name, url },
  ];

  return (
    <>
      <JsonLd
        data={[
          breadcrumbSchema(crumbs),
          collectionPageSchema({
            name: resolved.name,
            description: resolved.description ?? resolved.name,
            url,
          }),
        ]}
      />

      <Container className="pt-6">
        <Breadcrumbs crumbs={crumbs} />
      </Container>

      <EditorialHero
        entityId={resolved.id}
        eyebrow={typeLabel}
        title={resolved.name}
        subtitle={resolved.description}
        facts={[
          { label: "Type", value: typeLabel },
          { label: "Domain", value: resolved.domainLabel },
          { label: "Connections", value: resolved.relationCount || undefined },
          resolved.scientificName
            ? { label: "Scientific name", value: resolved.scientificName }
            : { label: "Catalog", value: resolved.catalogNumbers[0] },
        ]}
      />

      <Container className="mt-12 mb-12 space-y-14">
        <EntityImagery entityId={resolved.id} heading="Gallery" excludeHero />

        <div className="grid gap-6 lg:grid-cols-2">
          <EntityDataPanel resolved={resolved} />
          <EntityQualityPanel resolved={resolved} />
        </div>

        <div className="mt-6">
          <EntityProvenancePanel entityId={resolved.id} />
        </div>

        {hasConnections && (
          <section aria-labelledby="connections-heading">
            <h2 id="connections-heading" className="font-display text-xl font-semibold text-fg">
              Connections
            </h2>
            <p className="mt-1 text-sm text-faint">
              How {resolved.name} connects across Asteria Star — scientific,
              cultural, and astrological links are kept separate.
            </p>
            <div className="mt-4">
              <GraphConnections entityId={resolved.id} />
            </div>
          </section>
        )}

        {related.length > 0 && (
          <RelatedObjects heading="Related objects" items={related.map((e) => ({ id: e.id, name: e.name }))} />
        )}

        {siblings.length > 0 && (
          <RelatedObjects heading={`More ${typeLabel.toLowerCase()}s`} items={siblings.map((e) => ({ id: e.id, name: e.name }))} />
        )}

        <EntityRecommendations entityId={resolved.id} />

        {resolved.sources.length > 0 && (
          <SourceList keys={resolved.sources.map((s) => s.key)} />
        )}
      </Container>
    </>
  );
}
