import type { MetadataRoute } from "next";
import { SITE } from "@/lib/site";

/**
 * Web App Manifest (served at /manifest.webmanifest). Provides the PWA/Android
 * install metadata and icon set. The SVG favicon and Apple touch icon are
 * auto-wired by Next from src/app/icon.svg and src/app/apple-icon.png; this
 * supplies the Android/maskable PNGs (generated by scripts/generate-brand.ts).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE.name,
    short_name: SITE.shortName,
    description: SITE.description,
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#05060f",
    theme_color: "#05060f",
    icons: [
      { src: "/icon.svg", type: "image/svg+xml", sizes: "any" },
      { src: "/icons/icon-192.png", type: "image/png", sizes: "192x192", purpose: "any" },
      { src: "/icons/icon-512.png", type: "image/png", sizes: "512x512", purpose: "any" },
      { src: "/icons/maskable-512.png", type: "image/png", sizes: "512x512", purpose: "maskable" },
    ],
  };
}
