import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site";
import { absoluteUrl } from "@/lib/routes";

/**
 * robots.txt — the whole public site is crawlable. Reserved, not-yet-built
 * areas (the future authenticated product area and any API) are disallowed up
 * front so they never leak into the index later.
 *
 * TWO SITEMAPS, and that is the whole discovery mechanism for the blog.
 *
 * `asteriastar.com/blog` is served by a separate Netlify project with its own build, and its sitemap
 * is generated by that build. Naming both here means a crawler finds the publication's URLs through
 * a file this site already serves — without this site's sitemap having to enumerate them, and
 * therefore without this site rebuilding every time an article is published. The blog sitemap is a
 * URL, not a build input.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/app/", "/api/"],
    },
    sitemap: [absoluteUrl("/sitemap.xml"), absoluteUrl("/blog/sitemap.xml")],
    host: SITE_URL,
  };
}
