import type { SourceKey } from "@/lib/sources";

/**
 * Knowledge graph schema.
 *
 * The graph is the connective tissue of Asteria Star: entities (stars,
 * planets, missions, myths, symbols…) joined by typed relations. Its single
 * most important rule is that **scientific, cultural, and astrological
 * connections are typed separately** — every relation carries a `domain` and a
 * `confidence`, and the validator (validate.ts) refuses to let astrology or
 * interpretive links masquerade as confirmed science.
 */

/** Kinds of things the graph can describe. */
export const ENTITY_TYPES = [
  "star",
  "planet",
  "dwarf_planet",
  "exoplanet",
  "moon",
  "galaxy",
  "nebula",
  "constellation",
  "star_cluster",
  "black_hole",
  "asteroid",
  "comet",
  "asteroid_family",
  "minor_planet_group",
  "near_earth_object",
  "trojan_group",
  "orbital_resonance",
  "impact_event",
  "comet_family",
  "comet_class",
  "small_body_reservoir",
  "active_asteroid",
  "dormant_comet",
  "meteorite",
  "meteorite_class",
  "meteorite_group",
  "fireball",
  "impact_structure",
  "recovery_site",
  "meteor_shower",
  "eclipse",
  "catalog",
  "space_mission",
  "spacecraft",
  "launch_vehicle",
  "satellite",
  "space_telescope",
  "observatory",
  "astronomer",
  "mythology_figure",
  "mythology_story",
  "astrology_sign",
  "astrology_planet",
  "astrology_house",
  "astrology_aspect",
  "calculator",
  "glossary_term",
  "guide",
  "article",
  "image_asset",
  "observation_event",
  "location",
  "surface_feature",
  "ring_system",
  "organization",
  "mission_program",
  "launch_site",
  "astronaut",
  "scientific_instrument",
  "space_station",
  "station_module",
  "human_spaceflight_program",
  "crew_vehicle",
  "cargo_vehicle",
  "expedition",
  "eva",
  "docking_system",
  "life_support_system",
  "space_experiment",
  "space_medicine_topic",
  "telescope",
  "sky_survey",
  "wavelength_band",
  "observing_site",
  "planetary_system",
  "host_star",
  "exoplanet_detection_method",
  "exoplanet_survey",
  "exoplanet_catalogue",
  "habitable_zone_candidate",
  "planetary_class",
  "historical_discovery",
  "publication",
  "astronomical_theory",
  "astronomy_era",
  "historical_event",
  "scientific_award",
  "cosmology_concept",
  "cosmological_model",
  "astrophysical_object_class",
  "observational_program",
  "scientific_image",
  "image_collection",
  "image_license",
  "image_source",
  // Rockets & Launch Vehicles (Program V). launch_vehicle/launch_site/organization/
  // mission_program already exist and are reused; these are the genuinely-new types.
  "rocket_family",
  "rocket_stage",
  "rocket_engine",
  "propellant",
  "launch_pad",
  // Constellation Encyclopedia (Program W). `constellation` already exists and is
  // reused for all 88; these group/pattern/season concepts are the new types.
  "constellation_family",
  "asterism",
  "seasonal_sky",
  // Satellite Encyclopedia (Program X). `satellite` already exists and is reused;
  // these are the new group/orbit/network types.
  "satellite_constellation",
  "orbit_type",
  "tracking_network",
  // Interstellar & Hyperbolic Objects (Program AB). Reuses comet / comet_class /
  // sky_survey / observatory / organization; these are the genuinely-new types. A
  // confirmed interstellar object and a candidate are typed separately so the two are
  // never conflated in the graph, in queries, or on a page.
  "interstellar_object",
  "interstellar_candidate",
  "hyperbolic_comet",
  "interstellar_detection_method",
  "trajectory_class",
  // Small-Body Missions & Sample Return (Program AC). Missions REUSE space_mission
  // (existing ones enriched, concepts/planned created); asteroids/comets/rockets/orgs
  // are reused. These are the genuinely-new mission-layer types.
  "mission_class",
  "returned_sample",
  "sample_return_capsule",
  "mission_phase",
  "science_campaign",
  // Deep Space Communications & Navigation (Program AD). Networks REUSE the existing
  // tracking_network type (DSN / Estrack / Near Space Network already exist); missions,
  // spacecraft, and organizations are reused. These are the genuinely-new infrastructure
  // types.
  "tracking_station",
  "ground_station",
  "antenna",
  "signal_band",
  "navigation_system",
  "time_standard",
  "communication_system",
  // Space Environment & Hazards (Program AE). Reuses the Sun, planets, moons, solar
  // missions, and NOAA/NASA; these are the genuinely-new hazard-layer types.
  "space_weather_phenomenon",
  "radiation_environment",
  "space_hazard",
  "geomagnetic_index",
  // Ground Segment & Mission Operations (Program AF). Reuses organizations, tracking
  // networks, and missions; these are the new operational types.
  "mission_operations_center",
  "operations_function",
  // Spacecraft Systems & Engineering (Program AG). Reuses docking_system, life_support_system,
  // antenna, and navigation_system; these are the new engineering types.
  "spacecraft_subsystem",
  "spacecraft_component",
  // Scientific Instruments & Payloads (Program AH). Reuses scientific_instrument and the
  // host missions and telescopes; instrument_class is the new grouping type.
  "instrument_class",
  // Planetary Geology & Surface Features (Program AI). Reuses surface_feature and the
  // planets, moons, and dwarf planets; geological_feature_type is the new grouping type.
  "geological_feature_type",
  // Space Agencies, Institutions & Laboratories (Program AJ). Reuses the many organization
  // entities (agencies, commercial companies, observatory operators); institution_type is
  // the new grouping type that classifies them.
  "institution_type",
  // Space Missions Timeline & Historical Events (Program AK). Reuses the missions, programs,
  // astronauts, stations, and telescopes; these are the new chronology entities — eras
  // (historic_space_event), dated events, milestone firsts, and standing records.
  "historic_space_event",
  "timeline_event",
  "mission_milestone",
  "record",
  // Life Support, Space Biology & Space Medicine (Program AL). Reuses the ECLSS system, the
  // radiation environments, the stations, and the astronauts; these are the new human-in-space
  // types — disciplines, physiological effects, life-support technologies, and countermeasures.
  "space_biology_topic",
  "physiological_effect",
  "life_support_technology",
  "countermeasure",
  // Space Manufacturing & In-Space Infrastructure (Program AM). Reuses the Moon, Mars, metal
  // asteroids, commercial/inflatable stations, propellants, and components; these are the new
  // future-engineering types — domains, ISRU techniques, manufacturing processes, and systems.
  "infrastructure_domain",
  "isru_technique",
  "space_manufacturing_process",
  "space_infrastructure",
  // Future Space Exploration & Mission Concepts (Program AN). Reuses in-development missions,
  // agencies, and target bodies; these are the new future-exploration types — themes and the
  // planned mission concepts not yet modelled.
  "exploration_theme",
  "mission_concept",
  // Astronomy Methods, Measurements & Scientific Techniques (Program AO). Reuses the
  // exoplanet-detection methods, cosmology concepts, and observing bands; these are the new
  // methods layer — method categories and the measurement/observation techniques.
  "method_category",
  "astronomy_method",
] as const;
export type EntityType = (typeof ENTITY_TYPES)[number];

/** Ways entities can be connected. */
export const RELATION_TYPES = [
  "belongs_to",
  "part_of",
  "located_in",
  "visible_from",
  "observed_by",
  "discovered_by",
  "named_after",
  "associated_with",
  "mythologically_linked_to",
  "astrologically_associated_with",
  "scientifically_related_to",
  "mission_target",
  "operated_by",
  "launched_by",
  "studies",
  "explains",
  "references",
  "has_calculator",
  "has_gallery",
  "has_timeline",
  "related_to",
  "parent_of",
  "child_of",
  "belongs_to_constellation",
  "part_of_star_system",
  "binary_with",
  "member_of_cluster",
  "hosts_exoplanet",
  "catalogued_in",
  "orbits",
  "belongs_to_planet",
  "target_of_mission",
  "part_of_mission",
  "visited_by",
  "landed_on",
  "located_on",
  "located_in_constellation",
  "member_of_group",
  "neighbor_of",
  "photographed_by",
  "related_survey",
  "part_of_program",
  "launched_from",
  "carried_by",
  "orbited",
  "visited",
  "returned_samples_from",
  "shares_orbital_resonance",
  "belongs_to_reservoir",
  "source_of_meteor_shower",
  "parent_body",
  "captured_image_of",
  "contains_instrument",
  "used_instrument",
  "performed_experiment",
  "supports_science",
  "preceded_by",
  "followed_by",
  "part_of_station",
  "attached_to",
  "docked_with",
  "visited_station",
  "served_on_expedition",
  "commanded_expedition",
  "performed_eva",
  "launched_aboard",
  "returned_aboard",
  "crewed_by",
  "carried_crew",
  "carried_cargo",
  "supported_by",
  "replaced_by",
  "built_by",
  "located_at",
  "part_of_observatory",
  "hosts_telescope",
  "uses_instrument",
  "has_instrument",
  "observes_band",
  "observed_object",
  "conducts_survey",
  "part_of_survey",
  "surveyed_by",
  "related_discovery",
  "predecessor_of",
  "successor_of",
  "orbits_star",
  "member_of_planetary_system",
  "discovered_by_method",
  "discovered_by_facility",
  "discovered_by_mission",
  "studied_by",
  "similar_to",
  "candidate_for_habitable_zone",
  "part_of_catalogue",
  "discovered",
  "predicted",
  "published",
  "developed",
  "observed",
  "worked_at",
  "collaborated_with",
  "influenced",
  "student_of",
  "teacher_of",
  "received_award",
  "introduced",
  "invented",
  "first_observed",
  "confirmed",
  "refuted",
  "supports",
  "predicts",
  "confirmed_by",
  "measured_by",
  "derived_from",
  "depends_on",
  "part_of_model",
  "contradicted_by",
  "requires",
  "contains",
  "formed_from",
  "evolved_into",
  "depicts",
  "captured_by",
  "taken_with",
  "taken_at",
  "processed_by",
  "published_by",
  "licensed_by",
  "documents",
  "derived_from_image",
  "part_of_collection",
  // Rockets & Launch Vehicles (Program V). Reuse existing operated_by / built_by /
  // launched_from / part_of_program / derived_from / replaced_by / preceded_by /
  // followed_by / part_of where they already fit; these four have no equivalent.
  "member_of_family",
  "has_stage",
  "powered_by",
  "uses_propellant",
  // Constellation Encyclopedia (Program W). Reuse existing belongs_to_constellation
  // / located_in_constellation / neighbor_of / associated_with /
  // mythologically_linked_to; these two have no equivalent.
  "belongs_to_family",
  "best_observed_in",
  // Satellite Encyclopedia (Program X). Reuse operated_by / launched_by /
  // launched_from / part_of_program / contains_instrument / belongs_to_constellation /
  // replaced_by / part_of; only orbit membership has no equivalent.
  "has_orbit",
  // Interstellar & Hyperbolic Objects (Program AB). Reuse surveyed_by (detected by a
  // survey) / observed_by / catalogued_in (reported to MPC / JPL) / associated_with
  // (detection method, related comet class) / studied_by / related_to; only the
  // trajectory-class classification (elliptical → hyperbolic → interstellar) has no
  // existing equivalent.
  "has_trajectory_class",
  // Small-Body Missions & Sample Return (Program AC). Reuse visited / orbited /
  // landed_on / returned_samples_from / member_of_group / launched_by / operated_by /
  // part_of_mission / followed_by / associated_with; only a deliberate kinetic impact
  // and the mission→returned-sample link have no existing equivalent.
  "impacted",
  "collected_sample",
  // Deep Space Communications & Navigation (Program AD). Reuse part_of (station→network),
  // operated_by, located_at (antenna→station), and associated_with; only tracking a
  // mission and operating in a communication band have no existing equivalent.
  "tracks",
  "uses_band",
  // Space Environment & Hazards (Program AE). Reuse observed_by (monitoring), associated_with,
  // and part_of; only a hazard affecting a body/mission has no existing equivalent.
  "affects",
  // Life Support, Space Biology & Space Medicine (Program AL). Reuse member_of_group,
  // part_of, and associated_with; only a countermeasure mitigating a physiological effect
  // has no existing equivalent.
  "mitigates",
] as const;
export type RelationType = (typeof RELATION_TYPES)[number];

/** The realm a relation (or entity) belongs to. The boundary is structural. */
export const DOMAINS = ["science", "culture", "astrology", "editorial"] as const;
export type Domain = (typeof DOMAINS)[number];

/** Entities live in one of the knowledge realms (never "editorial"). */
export const ENTITY_DOMAINS = ["science", "culture", "astrology"] as const;
export type EntityDomain = (typeof ENTITY_DOMAINS)[number];

/** How well-established a relation is. */
export const CONFIDENCES = ["confirmed", "likely", "interpretive"] as const;
export type Confidence = (typeof CONFIDENCES)[number];

export interface GraphEntity {
  /** Stable id, conventionally `type:slug` (e.g. "star:sirius"). */
  id: string;
  type: EntityType;
  name: string;
  domain: EntityDomain;
  description?: string;
  /** Canonical path of this entity's content entry, if one exists. */
  entryPath?: string;
  aliases?: string[];
  sources?: SourceKey[];

  /* --- Optional intelligence fields. Left empty when a value is unknown;
     never invented. --- */
  /** Formal scientific designation (e.g. "Alpha Canis Majoris"). */
  scientificName?: string;
  /** Catalog designations (e.g. ["M31", "NGC 224"]). */
  catalogNumbers?: string[];
  /** Cross-reference ids/links to external identifiers. */
  crossReferences?: string[];
  /** Editorial significance hint (1–5) for ordering; optional, never fabricated science. */
  importance?: number;
}

export interface GraphRelation {
  /** Stable id, conventionally `from|type|to`. */
  id: string;
  from: string;
  to: string;
  type: RelationType;
  confidence: Confidence;
  domain: Domain;
  sources?: SourceKey[];
  note?: string;
}

/* ------------------------------------------------- domain typing rules */

/** Relation types that may ONLY be used in the science domain. */
export const SCIENCE_ONLY_RELATIONS: ReadonlySet<RelationType> = new Set([
  "belongs_to",
  "part_of",
  "located_in",
  "visible_from",
  "observed_by",
  "discovered_by",
  "mission_target",
  "operated_by",
  "launched_by",
  "studies",
  "scientifically_related_to",
  "belongs_to_constellation",
  "part_of_star_system",
  "binary_with",
  "member_of_cluster",
  "hosts_exoplanet",
  "catalogued_in",
  "orbits",
  "belongs_to_planet",
  "target_of_mission",
  "part_of_mission",
  "visited_by",
  "landed_on",
  "located_on",
  "located_in_constellation",
  "member_of_group",
  "neighbor_of",
  "photographed_by",
  "related_survey",
  "part_of_program",
  "launched_from",
  "carried_by",
  "orbited",
  "visited",
  "returned_samples_from",
  "shares_orbital_resonance",
  "belongs_to_reservoir",
  "source_of_meteor_shower",
  "parent_body",
  "captured_image_of",
  "contains_instrument",
  "used_instrument",
  "performed_experiment",
  "supports_science",
  "preceded_by",
  "followed_by",
  "part_of_station",
  "attached_to",
  "docked_with",
  "visited_station",
  "served_on_expedition",
  "commanded_expedition",
  "performed_eva",
  "launched_aboard",
  "returned_aboard",
  "crewed_by",
  "carried_crew",
  "carried_cargo",
  "supported_by",
  "replaced_by",
  "built_by",
  "located_at",
  "part_of_observatory",
  "hosts_telescope",
  "uses_instrument",
  "has_instrument",
  "observes_band",
  "observed_object",
  "conducts_survey",
  "part_of_survey",
  "surveyed_by",
  "related_discovery",
  "predecessor_of",
  "successor_of",
  "orbits_star",
  "member_of_planetary_system",
  "discovered_by_method",
  "discovered_by_facility",
  "discovered_by_mission",
  "studied_by",
  "similar_to",
  "candidate_for_habitable_zone",
  "part_of_catalogue",
  "discovered",
  "predicted",
  "published",
  "developed",
  "observed",
  "worked_at",
  "collaborated_with",
  "influenced",
  "student_of",
  "teacher_of",
  "received_award",
  "introduced",
  "invented",
  "first_observed",
  "confirmed",
  "refuted",
  "supports",
  "predicts",
  "confirmed_by",
  "measured_by",
  "derived_from",
  "depends_on",
  "part_of_model",
  "contradicted_by",
  "requires",
  "contains",
  "formed_from",
  "evolved_into",
  "depicts",
  "captured_by",
  "taken_with",
  "taken_at",
  "processed_by",
  "published_by",
  "licensed_by",
  "documents",
  "derived_from_image",
  "part_of_collection",
  "member_of_family",
  "has_stage",
  "powered_by",
  "uses_propellant",
  "belongs_to_family",
  "best_observed_in",
  "has_orbit",
  "has_trajectory_class",
  "impacted",
  "collected_sample",
  "tracks",
  "uses_band",
  "affects",
  "mitigates",
]);

/** Relation types that may ONLY be used in the astrology domain. */
export const ASTROLOGY_ONLY_RELATIONS: ReadonlySet<RelationType> = new Set([
  "astrologically_associated_with",
]);

/** Relation types that may ONLY be used in the culture domain. */
export const CULTURE_ONLY_RELATIONS: ReadonlySet<RelationType> = new Set([
  "mythologically_linked_to",
]);

/** Build a stable relation id from its endpoints and type. */
export function makeRelationId(
  from: string,
  type: RelationType,
  to: string,
): string {
  return `${from}|${type}|${to}`;
}

/** Concise relation builder used by the graph data modules. */
export function rel(
  from: string,
  type: RelationType,
  to: string,
  confidence: Confidence,
  domain: Domain,
  extra: { sources?: SourceKey[]; note?: string } = {},
): GraphRelation {
  return { id: makeRelationId(from, type, to), from, to, type, confidence, domain, ...extra };
}

/* ------------------------------------------------------- display labels */

export const RELATION_LABELS: Record<RelationType, string> = {
  belongs_to: "Belongs to",
  part_of: "Part of",
  located_in: "Located in",
  visible_from: "Visible from",
  observed_by: "Observed by",
  discovered_by: "Discovered by",
  named_after: "Named after",
  associated_with: "Associated with",
  mythologically_linked_to: "Linked in myth to",
  astrologically_associated_with: "Associated with (astrology)",
  scientifically_related_to: "Scientifically related to",
  mission_target: "Mission target",
  operated_by: "Operated by",
  launched_by: "Launched by",
  studies: "Studies",
  explains: "Explains",
  references: "References",
  has_calculator: "Has calculator",
  has_gallery: "Has gallery",
  has_timeline: "Has timeline",
  related_to: "Related to",
  parent_of: "Parent of",
  child_of: "Child of",
  belongs_to_constellation: "In constellation",
  part_of_star_system: "Part of system",
  binary_with: "Binary with",
  member_of_cluster: "Member of cluster",
  hosts_exoplanet: "Hosts exoplanet",
  catalogued_in: "Catalogued in",
  orbits: "Orbits",
  belongs_to_planet: "Orbits",
  target_of_mission: "Target of",
  part_of_mission: "Part of mission",
  visited_by: "Visited by",
  landed_on: "Landed on",
  located_on: "Located on",
  located_in_constellation: "In constellation",
  member_of_group: "Member of group",
  neighbor_of: "Neighbour of",
  photographed_by: "Photographed by",
  related_survey: "Related survey",
  part_of_program: "Part of program",
  launched_from: "Launched from",
  carried_by: "Carried by",
  orbited: "Orbited",
  visited: "Visited",
  returned_samples_from: "Returned samples from",
  shares_orbital_resonance: "In orbital resonance",
  belongs_to_reservoir: "Source reservoir",
  source_of_meteor_shower: "Source of meteor shower",
  parent_body: "Parent body",
  captured_image_of: "Captured image of",
  contains_instrument: "Carries instrument",
  used_instrument: "Used instrument",
  performed_experiment: "Performed experiment",
  supports_science: "Supports science",
  preceded_by: "Preceded by",
  followed_by: "Followed by",
  part_of_station: "Part of station",
  attached_to: "Attached to",
  docked_with: "Docked with",
  visited_station: "Visited",
  served_on_expedition: "Served on",
  commanded_expedition: "Commanded",
  performed_eva: "Performed",
  launched_aboard: "Launched aboard",
  returned_aboard: "Returned aboard",
  crewed_by: "Crewed by",
  carried_crew: "Carried crew",
  carried_cargo: "Carried cargo",
  supported_by: "Supported by",
  replaced_by: "Replaced by",
  built_by: "Built by",
  located_at: "Located at",
  part_of_observatory: "Part of",
  hosts_telescope: "Hosts",
  uses_instrument: "Uses instrument",
  has_instrument: "Has instrument",
  observes_band: "Observes",
  observed_object: "Observed",
  conducts_survey: "Conducts survey",
  part_of_survey: "Part of survey",
  surveyed_by: "Surveyed by",
  related_discovery: "Related discovery",
  predecessor_of: "Predecessor of",
  successor_of: "Successor of",
  orbits_star: "Orbits",
  member_of_planetary_system: "Member of system",
  discovered_by_method: "Discovered by method",
  discovered_by_facility: "Discovered at",
  discovered_by_mission: "Discovered by mission",
  studied_by: "Studied by",
  similar_to: "Similar to",
  candidate_for_habitable_zone: "Habitable-zone candidate",
  part_of_catalogue: "Catalogued in",
  discovered: "Discovered",
  predicted: "Predicted",
  published: "Published",
  developed: "Developed",
  observed: "Observed",
  worked_at: "Worked at",
  collaborated_with: "Collaborated with",
  influenced: "Influenced",
  student_of: "Student of",
  teacher_of: "Teacher of",
  received_award: "Received",
  introduced: "Introduced",
  invented: "Invented",
  first_observed: "First observed",
  confirmed: "Confirmed",
  refuted: "Refuted",
  supports: "Supports",
  predicts: "Predicts",
  confirmed_by: "Confirmed by",
  measured_by: "Measured by",
  derived_from: "Derived from",
  depends_on: "Depends on",
  part_of_model: "Part of model",
  contradicted_by: "Contradicted by",
  requires: "Requires",
  contains: "Contains",
  formed_from: "Formed from",
  evolved_into: "Evolved into",
  depicts: "Depicts",
  captured_by: "Captured by",
  taken_with: "Taken with",
  taken_at: "Taken at",
  processed_by: "Processed by",
  published_by: "Published by",
  licensed_by: "Licensed under",
  documents: "Documents",
  derived_from_image: "Derived from",
  part_of_collection: "Part of collection",
  member_of_family: "Member of family",
  has_stage: "Has stage",
  powered_by: "Powered by",
  uses_propellant: "Uses propellant",
  belongs_to_family: "Belongs to family",
  best_observed_in: "Best observed in",
  has_orbit: "Orbit",
  has_trajectory_class: "Trajectory class",
  impacted: "Impacted",
  collected_sample: "Collected sample",
  tracks: "Tracks",
  uses_band: "Uses band",
  affects: "Affects",
  mitigates: "Mitigates",
};

/** Labels for when the current entity is the *target* (incoming relation). */
export const INVERSE_RELATION_LABELS: Record<RelationType, string> = {
  belongs_to: "Includes",
  part_of: "Contains",
  located_in: "Contains",
  visible_from: "Visible location for",
  observed_by: "Observes",
  discovered_by: "Discovered",
  named_after: "Namesake of",
  associated_with: "Associated with",
  mythologically_linked_to: "Linked in myth to",
  astrologically_associated_with: "Associated with (astrology)",
  scientifically_related_to: "Scientifically related to",
  mission_target: "Target of",
  operated_by: "Operates",
  launched_by: "Launched",
  studies: "Studied by",
  explains: "Explained by",
  references: "Referenced by",
  has_calculator: "Calculator for",
  has_gallery: "Gallery for",
  has_timeline: "Timeline for",
  related_to: "Related to",
  parent_of: "Child of",
  child_of: "Parent of",
  belongs_to_constellation: "Constellation of",
  part_of_star_system: "System includes",
  binary_with: "Binary with",
  member_of_cluster: "Cluster includes",
  hosts_exoplanet: "Orbits",
  catalogued_in: "Catalogues",
  orbits: "Orbited by",
  belongs_to_planet: "Moon of",
  target_of_mission: "Targets",
  part_of_mission: "Mission includes",
  visited_by: "Visited",
  landed_on: "Landing site of",
  located_on: "Has feature",
  located_in_constellation: "Contains object",
  member_of_group: "Group includes",
  neighbor_of: "Neighbour of",
  photographed_by: "Photographed",
  related_survey: "Survey of",
  part_of_program: "Program includes",
  launched_from: "Launch site for",
  carried_by: "Carried",
  orbited: "Orbited by",
  visited: "Visited by",
  returned_samples_from: "Samples returned by",
  shares_orbital_resonance: "Resonance shared by",
  belongs_to_reservoir: "Reservoir of",
  source_of_meteor_shower: "Meteor shower of parent",
  parent_body: "Parent body of",
  captured_image_of: "Imaged by",
  contains_instrument: "Instrument on",
  used_instrument: "Instrument used by",
  performed_experiment: "Experiment performed by",
  supports_science: "Science supported by",
  preceded_by: "Followed by",
  followed_by: "Preceded by",
  part_of_station: "Station component",
  attached_to: "Has attached",
  docked_with: "Docked with",
  visited_station: "Visited by",
  served_on_expedition: "Crew member",
  commanded_expedition: "Commanded by",
  performed_eva: "Performed by",
  launched_aboard: "Launch crew",
  returned_aboard: "Return crew",
  crewed_by: "Crew of",
  carried_crew: "Carried by",
  carried_cargo: "Cargo carried by",
  supported_by: "Supports",
  replaced_by: "Replaced",
  built_by: "Built",
  located_at: "Location of",
  part_of_observatory: "Includes",
  hosts_telescope: "Hosted at",
  uses_instrument: "Used by",
  has_instrument: "Instrument of",
  observes_band: "Observed by",
  observed_object: "Observed by",
  conducts_survey: "Conducted by",
  part_of_survey: "Includes",
  surveyed_by: "Surveyed",
  related_discovery: "Discovered via",
  predecessor_of: "Successor of",
  successor_of: "Predecessor of",
  orbits_star: "Orbited by",
  member_of_planetary_system: "System includes",
  discovered_by_method: "Method for",
  discovered_by_facility: "Discovery facility for",
  discovered_by_mission: "Discovered",
  studied_by: "Studies",
  similar_to: "Similar to",
  candidate_for_habitable_zone: "Habitable-zone candidate of",
  part_of_catalogue: "Catalogue includes",
  discovered: "Discovered by",
  predicted: "Predicted by",
  published: "Published by",
  developed: "Developed by",
  observed: "Observed by",
  worked_at: "Workplace of",
  collaborated_with: "Collaborated with",
  influenced: "Influenced by",
  student_of: "Teacher of",
  teacher_of: "Student of",
  received_award: "Awarded to",
  introduced: "Introduced by",
  invented: "Invented by",
  first_observed: "First observed by",
  confirmed: "Confirmed by",
  refuted: "Refuted by",
  supports: "Supported by",
  predicts: "Predicted by",
  confirmed_by: "Confirms",
  measured_by: "Measures",
  derived_from: "Basis for",
  depends_on: "Required by",
  part_of_model: "Includes",
  contradicted_by: "Contradicts",
  requires: "Required by",
  contains: "Part of",
  formed_from: "Formed into",
  evolved_into: "Evolved from",
  depicts: "Depicted in",
  captured_by: "Captured",
  taken_with: "Used for",
  taken_at: "Imaging location for",
  processed_by: "Processed",
  published_by: "Published",
  licensed_by: "License for",
  documents: "Documented in",
  derived_from_image: "Source for",
  part_of_collection: "Includes image",
  member_of_family: "Family includes",
  has_stage: "Stage of",
  powered_by: "Powers",
  uses_propellant: "Propellant of",
  belongs_to_family: "Family includes",
  best_observed_in: "Best season for",
  has_orbit: "Orbit of",
  has_trajectory_class: "Trajectory class of",
  impacted: "Impacted by",
  collected_sample: "Collected by",
  tracks: "Tracked by",
  uses_band: "Used by",
  affects: "Affected by",
  mitigates: "Mitigated by",
};

/** Pick the readable label for a relation given the viewing direction. */
export function relationLabel(type: RelationType, outgoing: boolean): string {
  return outgoing ? RELATION_LABELS[type] : INVERSE_RELATION_LABELS[type];
}

/**
 * Connection facets — finer grouping than domain, so entity pages can show
 * Scientific / Observational / Mission / Discovery / Related groups (science)
 * plus Cultural and Astrology, never mixed.
 */
export type ConnectionFacet =
  | "scientific"
  | "observational"
  | "mission"
  | "discovery"
  | "related"
  | "cultural"
  | "astrology";

export const FACET_LABELS: Record<ConnectionFacet, string> = {
  scientific: "Scientific connections",
  observational: "Observational connections",
  mission: "Mission connections",
  discovery: "Discovery connections",
  related: "Related",
  cultural: "Cultural & mythological connections",
  astrology: "Astrology / symbolic connections",
};

/** Ordered facets for rendering. */
export const FACET_ORDER: ConnectionFacet[] = [
  "scientific",
  "observational",
  "mission",
  "discovery",
  "related",
  "cultural",
  "astrology",
];

/** Classify a relation into a connection facet. */
export function relationFacet(domain: Domain, type: RelationType): ConnectionFacet {
  if (domain === "astrology") return "astrology";
  if (domain === "culture") return "cultural";
  // science / editorial
  if (["observed_by", "studies", "visible_from", "photographed_by", "related_survey", "observes_band", "observed_object", "conducts_survey", "part_of_survey", "surveyed_by", "uses_instrument", "has_instrument", "observed", "first_observed"].includes(type)) return "observational";
  if (["mission_target", "operated_by", "launched_by", "target_of_mission", "part_of_mission", "visited_by", "landed_on", "part_of_program", "launched_from", "carried_by", "orbited", "visited", "returned_samples_from", "captured_image_of", "part_of_station", "attached_to", "docked_with", "visited_station", "served_on_expedition", "commanded_expedition", "performed_eva", "launched_aboard", "returned_aboard", "crewed_by", "carried_crew", "carried_cargo", "impacted", "collected_sample", "tracks"].includes(type)) return "mission";
  if (["observed_by", "measured_by", "captured_by", "taken_with", "taken_at"].includes(type)) return "observational";
  if (["discovered_by", "named_after", "catalogued_in", "discovered_by_method", "discovered_by_facility", "discovered_by_mission", "part_of_catalogue", "discovered", "predicted", "confirmed", "refuted", "introduced", "invented", "developed", "published", "predicts", "confirmed_by", "contradicted_by", "depicts", "documents"].includes(type)) return "discovery";
  if (["scientifically_related_to", "related_to", "references", "belongs_to_constellation", "part_of_star_system", "binary_with", "member_of_cluster", "hosts_exoplanet", "orbits", "belongs_to_planet", "located_on", "located_in_constellation", "member_of_group", "neighbor_of", "contains_instrument", "used_instrument", "performed_experiment", "supports_science", "preceded_by", "followed_by", "supported_by", "replaced_by", "built_by", "located_at", "part_of_observatory", "hosts_telescope", "related_discovery", "predecessor_of", "successor_of", "orbits_star", "member_of_planetary_system", "similar_to", "candidate_for_habitable_zone", "supports", "derived_from", "depends_on", "part_of_model", "requires", "contains", "formed_from", "evolved_into", "processed_by", "published_by", "licensed_by", "derived_from_image", "part_of_collection", "member_of_family", "has_stage", "powered_by", "uses_propellant", "belongs_to_family", "best_observed_in", "has_orbit", "shares_orbital_resonance", "belongs_to_reservoir", "source_of_meteor_shower", "parent_body", "has_trajectory_class", "uses_band", "affects", "mitigates"].includes(type)) return "related";
  return "scientific";
}

export const DOMAIN_LABELS: Record<Domain, string> = {
  science: "Scientific connections",
  culture: "Cultural & mythological connections",
  astrology: "Astrology / symbolic connections",
  editorial: "Editorial links",
};

/** Singular human-readable label per entity type. */
export const ENTITY_TYPE_LABELS: Record<EntityType, string> = {
  star: "Star",
  planet: "Planet",
  dwarf_planet: "Dwarf planet",
  exoplanet: "Exoplanet",
  moon: "Moon",
  galaxy: "Galaxy",
  nebula: "Nebula",
  constellation: "Constellation",
  star_cluster: "Star cluster",
  black_hole: "Black hole",
  asteroid: "Asteroid",
  comet: "Comet",
  asteroid_family: "Asteroid family",
  minor_planet_group: "Minor-planet group",
  near_earth_object: "Near-Earth object class",
  trojan_group: "Trojan group",
  orbital_resonance: "Orbital resonance",
  impact_event: "Impact event",
  comet_family: "Comet family",
  comet_class: "Comet class",
  small_body_reservoir: "Small-body reservoir",
  active_asteroid: "Active asteroid",
  dormant_comet: "Dormant comet",
  meteorite: "Meteorite",
  meteorite_class: "Meteorite class",
  meteorite_group: "Meteorite group",
  fireball: "Fireball",
  impact_structure: "Impact structure",
  recovery_site: "Recovery site",
  meteor_shower: "Meteor shower",
  eclipse: "Eclipse",
  catalog: "Catalog",
  space_mission: "Space mission",
  spacecraft: "Spacecraft",
  launch_vehicle: "Launch vehicle",
  satellite: "Satellite",
  space_telescope: "Space telescope",
  observatory: "Observatory",
  astronomer: "Astronomer",
  mythology_figure: "Mythological figure",
  mythology_story: "Mythological story",
  astrology_sign: "Zodiac sign",
  astrology_planet: "Astrological planet",
  astrology_house: "Astrological house",
  astrology_aspect: "Astrological aspect",
  calculator: "Calculator",
  glossary_term: "Glossary term",
  guide: "Guide",
  article: "Article",
  image_asset: "Image",
  observation_event: "Observation",
  location: "Location",
  surface_feature: "Surface feature",
  ring_system: "Ring system",
  organization: "Organization",
  mission_program: "Mission program",
  launch_site: "Launch site",
  astronaut: "Astronaut",
  scientific_instrument: "Scientific instrument",
  space_station: "Space station",
  station_module: "Station module",
  human_spaceflight_program: "Human spaceflight program",
  crew_vehicle: "Crewed spacecraft",
  cargo_vehicle: "Cargo spacecraft",
  expedition: "Expedition",
  eva: "Spacewalk (EVA)",
  docking_system: "Docking system",
  life_support_system: "Life-support system",
  space_experiment: "Space experiment",
  space_medicine_topic: "Space medicine",
  telescope: "Telescope",
  sky_survey: "Sky survey",
  wavelength_band: "Observing band",
  observing_site: "Observing site",
  planetary_system: "Planetary system",
  host_star: "Host star",
  exoplanet_detection_method: "Detection method",
  exoplanet_survey: "Exoplanet survey",
  exoplanet_catalogue: "Exoplanet catalogue",
  habitable_zone_candidate: "Habitable-zone candidate",
  planetary_class: "Planetary class",
  historical_discovery: "Discovery",
  publication: "Publication",
  astronomical_theory: "Theory",
  astronomy_era: "Era",
  historical_event: "Historical event",
  scientific_award: "Award",
  cosmology_concept: "Cosmology concept",
  cosmological_model: "Cosmological model",
  astrophysical_object_class: "Astrophysical object",
  observational_program: "Observational program",
  scientific_image: "Scientific image",
  image_collection: "Image collection",
  image_license: "Image license",
  image_source: "Image source",
  rocket_family: "Rocket family",
  rocket_stage: "Rocket stage",
  rocket_engine: "Rocket engine",
  propellant: "Propellant",
  launch_pad: "Launch pad",
  constellation_family: "Constellation family",
  asterism: "Asterism",
  seasonal_sky: "Seasonal sky",
  satellite_constellation: "Satellite constellation",
  orbit_type: "Orbit type",
  tracking_network: "Tracking network",
  interstellar_object: "Interstellar object",
  interstellar_candidate: "Interstellar candidate",
  hyperbolic_comet: "Hyperbolic comet",
  interstellar_detection_method: "Detection method",
  trajectory_class: "Trajectory class",
  mission_class: "Mission class",
  returned_sample: "Returned sample",
  sample_return_capsule: "Sample-return capsule",
  mission_phase: "Mission phase",
  science_campaign: "Science campaign",
  tracking_station: "Tracking station",
  ground_station: "Ground station",
  antenna: "Antenna",
  signal_band: "Signal band",
  navigation_system: "Navigation system",
  time_standard: "Time standard",
  communication_system: "Communication system",
  space_weather_phenomenon: "Space-weather phenomenon",
  radiation_environment: "Radiation environment",
  space_hazard: "Space hazard",
  geomagnetic_index: "Geomagnetic index",
  mission_operations_center: "Mission operations center",
  operations_function: "Operations function",
  spacecraft_subsystem: "Spacecraft subsystem",
  spacecraft_component: "Spacecraft component",
  instrument_class: "Instrument class",
  geological_feature_type: "Geological feature type",
  institution_type: "Institution type",
  historic_space_event: "Spaceflight era",
  timeline_event: "Timeline event",
  mission_milestone: "Mission milestone",
  record: "Record",
  space_biology_topic: "Space-biology discipline",
  physiological_effect: "Physiological effect",
  life_support_technology: "Life-support technology",
  countermeasure: "Countermeasure",
  infrastructure_domain: "Infrastructure domain",
  isru_technique: "ISRU technique",
  space_manufacturing_process: "Space manufacturing process",
  space_infrastructure: "Space infrastructure",
  exploration_theme: "Exploration theme",
  mission_concept: "Mission concept",
  method_category: "Method category",
  astronomy_method: "Astronomy method",
};
