/**
 * Program 2 — NED extragalactic ingestion.
 *
 * For every galaxy / galaxy-group object, queries the NASA/IPAC Extragalactic
 * Database ObjectLookup and records the preferred name, object type, position and
 * COSMOLOGICAL REDSHIFT (value, uncertainty, quality, bibcode) verbatim. NED is
 * extragalactic only, so Galactic objects are never sent here.
 *   npx tsx scripts/precision/ingest-ned-galaxies.ts
 */
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { writeFileSync, mkdirSync } from "node:fs";
import { DEEP_SKY_RECORDS } from "../../src/knowledge-graph/data/deep-sky-catalog";
import type { NedDeepSkyRow } from "../../src/knowledge-graph/data/deep-sky-catalog/precision/types";

const pExecFile = promisify(execFile);
const OUT = "src/knowledge-graph/data/deep-sky-catalog/precision/snapshots/ned-deep-sky.ts";
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const num = (v: unknown): number | null => (v == null || v === "" || !Number.isFinite(Number(v)) ? null : Number(v));
const str = (v: unknown): string | null => (v == null || v === "" ? null : String(v).trim() || null);

function queryId(r: (typeof DEEP_SKY_RECORDS)[number]): string | null {
  return r.ids.messier ?? r.ids.ngc ?? r.ids.ic ?? (r.ids.pgc ? `PGC ${r.ids.pgc}` : null);
}

async function lookup(name: string): Promise<Record<string, unknown> | null> {
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const { stdout } = await pExecFile(
        "curl", ["-sS", "--compressed", "--max-time", "40", "-G", "--data-urlencode", `name=${name}`, "https://ned.ipac.caltech.edu/srs/ObjectLookup"],
        { maxBuffer: 16 * 1024 * 1024, encoding: "utf8" },
      );
      const json = JSON.parse(stdout) as { Preferred?: Record<string, unknown>; ResultCode?: number };
      return json.Preferred ?? null;
    } catch {
      if (attempt === 3) return null;
      await sleep(1500 * attempt);
    }
  }
  return null;
}

async function main() {
  // NED is extragalactic: only galaxies / galaxy groups.
  const galaxies = DEEP_SKY_RECORDS.filter((r) => r.entityType === "galaxy").map((r) => ({ dsId: r.id, q: queryId(r) }))
    .filter((c): c is { dsId: string; q: string } => !!c.q);
  console.log(`NED: ${galaxies.length} extragalactic objects`);

  const rows: NedDeepSkyRow[] = [];
  let i = 0;
  for (const g of galaxies) {
    const p = await lookup(g.q);
    i++;
    if (p) {
      const pos = (p.Position ?? {}) as Record<string, unknown>;
      const z = (p.Redshift ?? {}) as Record<string, unknown>;
      const ot = (p.ObjType ?? {}) as Record<string, unknown>;
      rows.push({
        queryId: g.q, dsId: g.dsId, ned_name: str(p.Name), objtype: str(ot.Value),
        ra: num(pos.RA), dec: num(pos.Dec), pos_bibcode: str(pos.RefCode),
        redshift: num(z.Value), redshift_unc: num(z.Uncertainty), redshift_bibcode: str(z.RefCode), redshift_qual: str(z.QualityFlag),
      });
    }
    if (i % 20 === 0) console.log(`  ${i}/${galaxies.length} (matched: ${rows.length})`);
    await sleep(250);
  }

  rows.sort((a, b) => a.dsId.localeCompare(b.dsId));
  mkdirSync("src/knowledge-graph/data/deep-sky-catalog/precision/snapshots", { recursive: true });
  const header =
    `import type { NedDeepSkyRow } from "@/knowledge-graph/data/deep-sky-catalog/precision/types";\n\n` +
    `// Generated by scripts/precision/ingest-ned-galaxies.ts from the NASA/IPAC Extragalactic\n` +
    `// Database (ObjectLookup). Redshift/position carry NED's own RefCode bibcodes; null = no value.\n` +
    `// Do not edit by hand.\n\n` +
    `export const NED_DEEP_SKY_RETRIEVED_AT = ${JSON.stringify(new Date().toISOString().slice(0, 10))};\n\n` +
    `export const NED_DEEP_SKY_ROWS: NedDeepSkyRow[] = `;
  writeFileSync(OUT, header + JSON.stringify(rows, null, 0) + ";\n");
  console.log(`NED: wrote ${rows.length} rows → ${OUT}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
