/**
 * Program 1 — SIMBAD star-parameter ingestion.
 *
 * Deterministic, resumable, snapshot-based. For every star with a HIP identifier it
 * queries the SIMBAD TAP `basic` table and writes each value VERBATIM (with the
 * source's own per-field bibcodes) into a committed .ts snapshot. Nothing is
 * synthesised: a field SIMBAD does not provide is written as `null`.
 *
 *   npx tsx scripts/precision/ingest-simbad-stars.ts        # full refresh
 *   npx tsx scripts/precision/ingest-simbad-stars.ts --resume  # keep existing rows, fill gaps
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { STAR_RECORDS } from "../../src/knowledge-graph/data/star-catalog";
import type { SimbadStarRow } from "../../src/knowledge-graph/data/star-catalog/precision/types";
import { tapQuery } from "./tap";

const TAP = "https://simbad.cds.unistra.fr/simbad/sim-tap/sync";
const OUT = "src/knowledge-graph/data/star-catalog/precision/snapshots/simbad-stars.ts";
const BATCH = 300;
const RESUME = process.argv.includes("--resume");

const FIELDS = [
  "main_id", "ra", "dec", "coo_bibcode", "plx_value", "plx_err", "plx_bibcode",
  "pmra", "pmdec", "pm_bibcode", "rvz_radvel", "rvz_err", "rvz_bibcode",
  "sp_type", "sp_bibcode", "otype_txt",
];

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function queryBatch(hips: number[]): Promise<Map<number, Record<string, unknown>>> {
  const inList = hips.map((h) => `'HIP ${h}'`).join(",");
  const adql =
    `SELECT ${FIELDS.map((f) => `b.${f}`).join(", ")}, id.id AS hipid ` +
    `FROM basic AS b JOIN ident AS id ON id.oidref = b.oid WHERE id.id IN (${inList})`;
  const { cols, data } = await tapQuery(TAP, adql);
  const out = new Map<number, Record<string, unknown>>();
  for (const row of data) {
    const rec: Record<string, unknown> = Object.fromEntries(cols.map((c, i) => [c, row[i]]));
    const hip = Number(String(rec.hipid).replace("HIP ", "").trim());
    if (Number.isFinite(hip)) out.set(hip, rec);
  }
  return out;
}

function loadExisting(): Map<number, SimbadStarRow> {
  const m = new Map<number, SimbadStarRow>();
  if (!RESUME || !existsSync(OUT)) return m;
  const txt = readFileSync(OUT, "utf8");
  // Anchor on the data array (`… = […]`), not the `SimbadStarRow[]` type annotation.
  const start = txt.indexOf("= [") + 2;
  const end = txt.lastIndexOf("]");
  if (start < 1 || end < 0) return m;
  try {
    const rows = JSON.parse(txt.slice(start, end + 1)) as SimbadStarRow[];
    for (const r of rows) m.set(r.hip, r);
  } catch { /* ignore, refetch */ }
  return m;
}

async function main() {
  const cohort = STAR_RECORDS
    .map((r) => ({ starId: r.id, hip: Number(r.ids.hip) }))
    .filter((c) => Number.isFinite(c.hip));
  const byHip = new Map(cohort.map((c) => [c.hip, c.starId]));
  const existing = loadExisting();
  const todo = [...byHip.keys()].filter((h) => !existing.has(h));
  console.log(`SIMBAD: ${cohort.length} HIP stars; ${existing.size} cached; fetching ${todo.length}`);

  const rows = new Map<number, SimbadStarRow>(existing);
  for (let i = 0; i < todo.length; i += BATCH) {
    const batch = todo.slice(i, i + BATCH);
    const res = await queryBatch(batch);
    for (const hip of batch) {
      const rec = res.get(hip);
      if (!rec) continue; // SIMBAD had no match for this HIP → leave absent, never invent
      rows.set(hip, {
        hip, starId: byHip.get(hip)!,
        main_id: String(rec.main_id ?? ""),
        ra: num(rec.ra), dec: num(rec.dec), coo_bibcode: str(rec.coo_bibcode),
        plx_value: num(rec.plx_value), plx_err: num(rec.plx_err), plx_bibcode: str(rec.plx_bibcode),
        pmra: num(rec.pmra), pmdec: num(rec.pmdec), pm_bibcode: str(rec.pm_bibcode),
        rvz_radvel: num(rec.rvz_radvel), rvz_err: num(rec.rvz_err), rvz_bibcode: str(rec.rvz_bibcode),
        sp_type: str(rec.sp_type), sp_bibcode: str(rec.sp_bibcode), otype_txt: str(rec.otype_txt),
      });
    }
    console.log(`  ${Math.min(i + BATCH, todo.length)}/${todo.length} (matched so far: ${rows.size})`);
    await sleep(400);
  }

  const sorted = [...rows.values()].sort((a, b) => a.hip - b.hip);
  write(sorted);
  console.log(`SIMBAD: wrote ${sorted.length} rows → ${OUT}`);
}

const num = (v: unknown): number | null => (v == null || v === "" || !Number.isFinite(Number(v)) ? null : Number(v));
const str = (v: unknown): string | null => (v == null || v === "" ? null : String(v));

function write(rows: SimbadStarRow[]) {
  mkdirSync("src/knowledge-graph/data/star-catalog/precision/snapshots", { recursive: true });
  const header =
    `import type { SimbadStarRow } from "@/knowledge-graph/data/star-catalog/precision/types";\n\n` +
    `// Generated by scripts/precision/ingest-simbad-stars.ts from SIMBAD TAP (basic table).\n` +
    `// Every value is transcribed verbatim with its per-field bibcode; null = no source value.\n` +
    `// Do not edit by hand.\n\n` +
    `export const SIMBAD_RETRIEVED_AT = ${JSON.stringify(new Date().toISOString().slice(0, 10))};\n\n` +
    `export const SIMBAD_STAR_ROWS: SimbadStarRow[] = `;
  writeFileSync(OUT, header + JSON.stringify(rows, null, 0) + ";\n");
}

main().catch((e) => { console.error(e); process.exit(1); });
