/**
 * Program 1 — Gaia DR3 star-parameter ingestion.
 *
 * Deterministic, resumable, snapshot-based. Crossmatches each HIP star to Gaia DR3
 * via gaiadr3.hipparcos2_best_neighbour and records the source_id, astrometry,
 * astrophysical parameters (GSP-Phot) and Bailer-Jones (2021) distances VERBATIM.
 * Gaia is INCOMPLETE for the brightest stars (saturation): those simply have no row
 * and are left absent — never fabricated.
 *
 *   npx tsx scripts/precision/ingest-gaia-stars.ts [--resume]
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { STAR_RECORDS } from "../../src/knowledge-graph/data/star-catalog";
import type { GaiaStarRow } from "../../src/knowledge-graph/data/star-catalog/precision/types";
import { tapQuery } from "./tap";

const TAP = "https://gea.esac.esa.int/tap-server/tap/sync";
const OUT = "src/knowledge-graph/data/star-catalog/precision/snapshots/gaia-stars.ts";
const BATCH = 400;
const RESUME = process.argv.includes("--resume");
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function queryBatch(hips: number[]): Promise<Map<number, Record<string, unknown>>> {
  const inList = hips.join(",");
  // source_id is a 64-bit integer (~2e18) far above JS's 2^53 safe range: it MUST be
  // cast to text in the query, or JSON.parse would silently round it to a wrong id.
  const adql =
    `SELECT h.original_ext_source_id AS hip, CAST(g.source_id AS VARCHAR) AS source_id, g.ra, g.dec, g.parallax, g.parallax_error, ` +
    `g.pmra, g.pmdec, g.phot_g_mean_mag, g.bp_rp, g.ruwe, ap.teff_gspphot, ap.logg_gspphot, ap.mh_gspphot, ` +
    `ap.radius_gspphot, d.r_med_geo, d.r_med_photogeo ` +
    `FROM gaiadr3.hipparcos2_best_neighbour h JOIN gaiadr3.gaia_source g ON g.source_id = h.source_id ` +
    `LEFT JOIN gaiadr3.astrophysical_parameters ap ON ap.source_id = g.source_id ` +
    `LEFT JOIN external.gaiaedr3_distance d ON d.source_id = g.source_id ` +
    `WHERE h.original_ext_source_id IN (${inList})`;
  const { cols, data } = await tapQuery(TAP, adql);
  const out = new Map<number, Record<string, unknown>>();
  for (const row of data) {
    const rec = Object.fromEntries(cols.map((c, i) => [c, row[i]]));
    const hip = Number(rec.hip);
    if (Number.isFinite(hip)) out.set(hip, rec);
  }
  return out;
}

function loadExisting(): Map<number, GaiaStarRow> {
  const m = new Map<number, GaiaStarRow>();
  if (!RESUME || !existsSync(OUT)) return m;
  const txt = readFileSync(OUT, "utf8");
  // Anchor on the data array (`… = […]`), not the `GaiaStarRow[]` type annotation.
  const s = txt.indexOf("= [") + 2, e = txt.lastIndexOf("]");
  if (s < 1 || e < 0) return m;
  try { for (const r of JSON.parse(txt.slice(s, e + 1)) as GaiaStarRow[]) m.set(r.hip, r); } catch { /* refetch */ }
  return m;
}

const num = (v: unknown): number | null => (v == null || v === "" || !Number.isFinite(Number(v)) ? null : Number(v));

async function main() {
  const cohort = STAR_RECORDS
    .map((r) => ({ starId: r.id, hip: Number(r.ids.hip) }))
    .filter((c) => Number.isFinite(c.hip));
  const byHip = new Map(cohort.map((c) => [c.hip, c.starId]));
  const existing = loadExisting();
  const todo = [...byHip.keys()].filter((h) => !existing.has(h));
  console.log(`Gaia: ${cohort.length} HIP stars; ${existing.size} cached; querying ${todo.length}`);

  const rows = new Map<number, GaiaStarRow>(existing);
  for (let i = 0; i < todo.length; i += BATCH) {
    const batch = todo.slice(i, i + BATCH);
    const res = await queryBatch(batch);
    for (const hip of batch) {
      const rec = res.get(hip);
      if (!rec) continue; // no Gaia crossmatch (e.g. bright-star saturation) → leave absent
      rows.set(hip, {
        hip, starId: byHip.get(hip)!, source_id: String(rec.source_id),
        ra: num(rec.ra), dec: num(rec.dec), parallax: num(rec.parallax), parallax_error: num(rec.parallax_error),
        pmra: num(rec.pmra), pmdec: num(rec.pmdec), phot_g_mean_mag: num(rec.phot_g_mean_mag), bp_rp: num(rec.bp_rp),
        ruwe: num(rec.ruwe), teff_gspphot: num(rec.teff_gspphot), logg_gspphot: num(rec.logg_gspphot),
        mh_gspphot: num(rec.mh_gspphot), radius_gspphot: num(rec.radius_gspphot),
        r_med_geo: num(rec.r_med_geo), r_med_photogeo: num(rec.r_med_photogeo),
      });
    }
    console.log(`  ${Math.min(i + BATCH, todo.length)}/${todo.length} (Gaia matches: ${rows.size})`);
    await sleep(600);
  }

  const sorted = [...rows.values()].sort((a, b) => a.hip - b.hip);
  mkdirSync("src/knowledge-graph/data/star-catalog/precision/snapshots", { recursive: true });
  const header =
    `import type { GaiaStarRow } from "@/knowledge-graph/data/star-catalog/precision/types";\n\n` +
    `// Generated by scripts/precision/ingest-gaia-stars.ts from Gaia DR3 TAP\n` +
    `// (gaiadr3.gaia_source ⨝ astrophysical_parameters ⨝ external.gaiaedr3_distance,\n` +
    `//  crossmatched via gaiadr3.hipparcos2_best_neighbour). null = no source value.\n` +
    `// Do not edit by hand.\n\n` +
    `export const GAIA_RETRIEVED_AT = ${JSON.stringify(new Date().toISOString().slice(0, 10))};\n\n` +
    `export const GAIA_STAR_ROWS: GaiaStarRow[] = `;
  writeFileSync(OUT, header + JSON.stringify(sorted, null, 0) + ";\n");
  console.log(`Gaia: wrote ${sorted.length} rows → ${OUT}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
